local status_ok, configs = pcall(require, "nvim-treesitter.configs")
if not status_ok then
    return
end

local languages = {
	"agda",
	"astro",
	"bash",
	"beancount",
	"bibtex",
	"blueprint",
	"c",
	"c_sharp",
	"clojure",
	"cmake",
	"comment",
	"commonlisp",
	"cooklang",
	"cpp",
	"css",
	"cuda",
	"d",
	"dart",
	"devicetree",
	"diff",
	"dockerfile",
	"dot",
	"eex",
	"elixir",
	--[[ "elm", ]]
	"elvish",
	--[[ "embedded_template", ]]
	"erlang",
	"fennel",
	"fish",
	"foam",
	--[[ "fortran", ]]
	"fusion",
	"git_rebase",
	"gitattributes",
	"gitignore",
	"gleam",
	"glsl",
	"go",
	"gomod",
	"gowork",
	"graphql",
	--[[ "hack", ]]
	--[[ "haskell", ]]
	"hcl",
	"heex",
	"help",
	"hjson",
	"hlsl",
	"hocon",
	"html",
	"http",
	"java",
	"javascript",
	"jsdoc",
	"json",
	"json5",
	"jsonnet",
	"julia",
	"kotlin",
	"lalrpop",
	"latex",
	"ledger",
	"llvm",
	"lua",
	"m68k",
	"make",
	"markdown",
	"markdown_inline",
	"menhir",
	"meson",
	--[[ "nickel", ]]
	"ninja",
	"nix",
	"norg",
	"ocaml",
	"ocaml_interface",
	"ocamllex",
	--[[ "org", ]]
	"pascal",
	"perl",
	"php",
	"phpdoc",
	"pioasm",
	"prisma",
	"proto",
	"pug",
	"python",
	"ql",
	"qmljs",
	"r",
	"racket",
	"rasi",
	"regex",
	"rego",
	"rnoweb",
	"rst",
	"ruby",
	"rust",
	"scala",
	"scheme",
	"scss",
	"slint",
	"solidity",
	"sparql",
	"sql",
	"supercollider",
	"surface",
	"svelte",
	"swift",
	"sxhkdrc",
	"teal",
	"tiger",
	"tlaplus",
	"todotxt",
	"toml",
	"tsx",
	"turtle",
	"twig",
	--[[ "typescript", ]] -- removed to avoid collisions on .jsx files
	"v",
	"vala",
	"verilog",
	"vhs",
	"vim",
	"vue",
	"wgsl",
	"yaml",
	"yang",
	"zig",
}
configs.setup {
    ensure_installed = "all", -- one of "all", "maintained" (parses with maintainers), or a list of languages
    sync_install = false, -- install languages synchronously (only applied to 'ensure_installed')
    -- ignore_install = { "" }, -- list of parsers to ignore installing
    autopairs = {
        enable = true,
    },
    highlight = {
        enable = true, -- false will disable the whole extension
        -- disable = { "" }, -- list of languages that will be disabled
        additional_vim_regex_highlighting = true,
    },
    indent = { enable = true, disable = { "yaml", "lua", "go", "javascriptreact" } },
    context_commentstring = {
        enable = true,
        enable_autocmd = false,
    }
}
