general {
    output_format = "i3bar"
    colors = true
    interval = 1   # refresh every second
}

order += "cpu_usage"
order += "memory"
order += "disk /"
order += "time"

cpu_usage {
    format = "CPU: %usage"
}

memory {
    format = "RAM: %used / %total"
    threshold_degraded = "10%"
    format_degraded = "MEMORY: %free"
}

disk "/" {
    format = "Disk: %avail free"
}

time {
    format = "%a %b %d %T"
}
